dist: xenial
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libspatialindex-dev
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install .
script:
  - pytest -m travis

after_success:
  - cd docs; make html
  - touch _build/html/.nojekyll

deploy:
  provider: pages:git
  skip_cleanup: true
  local_dir: _build/html
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  edge: true
  on:
    branch: master #

deploy:
  provider: pypi
  docs_dir: docs/build/html
  username: $PYPI_USERNAME  # Set in the settings page of your repository, as a secure variable
  password: $PYPI_PASSWORD
  edge: true
  on:
    branch: master #
