name: Documentation

on:
  pull_request:
  release:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install -y pandoc
        python -m pip install setuptools --upgrade
        python -m pip install -r dev-requirements.txt
        python -m pip install -r requirements.txt

    - name: Builds documentation
      run: |
        cd docs
        make html
        cd ..

    - name: Keeps documentation on GitHub
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: docs/_build/
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

    - name: Deploy 🚀
      if: github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/_build/html # The folder the action should deploy.